---
title: "Codebook For GettingAndCleaningDataAssignemnt"
author: "David Taylor - taken from the Gistfile.Rmd template"
date: "23rd August 2015"
output:
  html_document:
    keep_md: yes
---

## Project Description
The aim of the projet is to take the "UCI HAR Dataset" provided at :

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

and produce from it a 'tidy' data set that xtracts only the measurements on the mean and standard deviation for each measurement
then creates an independent tidy data set with the average of each variable for each activity and each subject

##Study design and data processing

###Collection of the raw data
The orignal experiment and its associated data is described in the README.txt in the "UCI HAR Dataset" directory.
What is seen in there is split into training (2947 observations) and test (7352 observations) data sets.

These observations are split into three text files (subject<suffix>.txt, y<suffix>.txt and X<suffix>.txt where <suffix> is _test or _train)
where subject is the subject, y is the activity code and X is the summary data created from the "true" raw data in the Inertial signals
subdirectory.

Each activity code is described in the activity_labels.txt file - we need his to meaningfully interpret the data.
Each of the 561 data fields per row in the 'X' data file is described in the features.txt file

##Creating the tidy datafile

###Guide to create the tidy data file
To create the tidy data file you should execute the run_analysis.R script in the same working directory that you have
extracted the "UCI HAR Dataset" directory to.

###Cleaning of the data
The script merges the test and training data sets and identifies those 'features' of the 'X' records that have either
'mean' or 'std' in their desriptions See the README.md document for a fuller description of the code.
The activity codes are expanded to the fuller description from the activity_labels.txt file
Then a mean is calculated for each observation type within each subject.

##Description of the variables in the tiny_data.txt file
Apart from subject identifier (number 1 : 6 ) and activity (facttor w/ 6 levels "LAYING","SITTING",..: 1 2 3 4), the variable names remain as per the descriptions in the source features.txt and are dimensionless

subject
activity
tBodyAcc-mean()-X
tBodyAcc-mean()-Y
tBodyAcc-mean()-Z
tBodyAcc-std()-X
tBodyAcc-std()-Y
tBodyAcc-std()-Z
tGravityAcc-mean()-X
tGravityAcc-mean()-Y
tGravityAcc-mean()-Z
tGravityAcc-std()-X
tGravityAcc-std()-Y
tGravityAcc-std()-Z
tBodyAccJerk-mean()-X
tBodyAccJerk-mean()-Y
tBodyAccJerk-mean()-Z
tBodyAccJerk-std()-X
tBodyAccJerk-std()-Y
tBodyAccJerk-std()-Z
tBodyGyro-mean()-X
tBodyGyro-mean()-Y
tBodyGyro-mean()-Z
tBodyGyro-std()-X
tBodyGyro-std()-Y
tBodyGyro-std()-Z
tBodyGyroJerk-mean()-X
tBodyGyroJerk-mean()-Y
tBodyGyroJerk-mean()-Z
tBodyGyroJerk-std()-X
tBodyGyroJerk-std()-Y
tBodyGyroJerk-std()-Z
tBodyAccMag-mean()
tBodyAccMag-std()
tGravityAccMag-mean()
tGravityAccMag-std()
tBodyAccJerkMag-mean()
tBodyAccJerkMag-std()
tBodyGyroMag-mean()
tBodyGyroMag-std()
tBodyGyroJerkMag-mean()
tBodyGyroJerkMag-std()
fBodyAcc-mean()-X
fBodyAcc-mean()-Y
fBodyAcc-mean()-Z
fBodyAcc-std()-X
fBodyAcc-std()-Y
fBodyAcc-std()-Z
fBodyAcc-meanFreq()-X
fBodyAcc-meanFreq()-Y
fBodyAcc-meanFreq()-Z
fBodyAccJerk-mean()-X
fBodyAccJerk-mean()-Y
fBodyAccJerk-mean()-Z
fBodyAccJerk-std()-X
fBodyAccJerk-std()-Y
fBodyAccJerk-std()-Z
fBodyAccJerk-meanFreq()-X
fBodyAccJerk-meanFreq()-Y
fBodyAccJerk-meanFreq()-Z
fBodyGyro-mean()-X
fBodyGyro-mean()-Y
fBodyGyro-mean()-Z
fBodyGyro-std()-X
fBodyGyro-std()-Y
fBodyGyro-std()-Z
fBodyGyro-meanFreq()-X
fBodyGyro-meanFreq()-Y
fBodyGyro-meanFreq()-Z
fBodyAccMag-mean()
fBodyAccMag-std()
fBodyAccMag-meanFreq()
fBodyBodyAccJerkMag-mean()
fBodyBodyAccJerkMag-std()
fBodyBodyAccJerkMag-meanFreq()
fBodyBodyGyroMag-mean()
fBodyBodyGyroMag-std()
fBodyBodyGyroMag-meanFreq()
fBodyBodyGyroJerkMag-mean()
fBodyBodyGyroJerkMag-std()
fBodyBodyGyroJerkMag-meanFreq()

